version: "2.4"

services:
  docs:
    image: node:12-alpine
    init: true
    command: /bin/sh -c 'yarn --frozen-lockfile --no-bin-links --modules-folder /cachedir/node_modules && /cachedir/node_modules/vuepress/cli.js dev docs'
    volumes:
      - .:/app:ro
    environment:
      NODE_PATH: /cachedir/node_modules
      HOST: 0.0.0.0
    working_dir: /app
    ports:
      - "8080:8080"
      - "8081:8081"
