version: "2.4"

services:
  docs:
    image: node:10-alpine
    init: true
    command: /bin/sh -c 'yarn --frozen-lockfile --no-bin-links --modules-folder /cachedir/node_modules && node /cachedir/node_modules/vuepress/bin/vuepress.js dev docs'
    volumes:
      - .:/app:ro
    environment:
      NODE_PATH: /cachedir/node_modules
    working_dir: /app
    ports:
      - "8080:8080"