name: build

on:
  push:
    branches-ignore: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: docs/.vuepress/dist
  publish:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: git rm -r .
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"
          git config --global push.default simple
          git checkout HEAD -- CNAME
          git add -A
          git commit -m "Update GitHub pages from ${GITHUB_SHA}"
          git push
